---
layout: cv
title: Aayush Khanal's Resume
---

<div id="webaddress">
<a href="datascience@byui.edu">khanalaa@byui.edu</a>
| <a href="https://github.com/khanalaa">My git hub page</a>
| <a href="www.linkedin.com/in/aayushkhanal">Linkedin</a>
</div>


## Education

`Expected 2026`
**Bachelor's in Computer Science | Brigham Young University - Idaho**, Rexburg, ID

- 4.0 Major GPA

## Relavant courses
Intro to Programming, Discrete Mathematics, Intro to Databases, Intro to Cybersecurity, Technical Teamwork
Data Science Programming, Programming with Functions and Classes, Javascript, Computer Systems, Algoritmic Thinking

## Experience
`Sept 2023 - Dec 2023`
Late Night Carpet Cleaning Crew | Brigham Young University-Idaho | Rexburg, Idaho

- Excecuted late-night carpet cleaning duties across all buildings on campus, collaborating with team members to maintain cleanliness and sanitation standards promoting pleasant atmosphere through effective teamwork.
- Spearheaded team to surpass cleaning goals, achieving a 18% efficiency boost.
- Implemented rigorous safety measures and adherence to protocols, resulting in zero accidents during late-night shifts, ensuring the safety and well-being of crew members and building occupants.
`Oct 2022 - May 2023`
Librarian | University of Louisiana Monroe | Monroe, Louisiana

- Managed a diverse collection of over 15 library resources, accessibility and organizational efficiency.
- Initiated and oversaw a total of 22 library programs, led to a remarkable 18% increase in participation, engaging community in a variety of enriching activities and events.

### Skills
**Languages:** Python, Java.<br>
**Web Programming:** HTML, CSS, JavaScript, React.Js, Node.Js.<br>
**Databases:** MySQL, MongoDB.<br>
**Others:** Git, GitHub, Linux, Microsoft Office Suite.
 
### Projects

`Oct 2023 - oct 2023`
**Designer | My SQL Project**

- Implemented MySQL database to efficiently retrieve and organize data, boosting overall accessibility and data management.
- Established a rigorous data update schedule, resulting in a 95% reduction in outdated information, thus improving project accuracy and relevance.

`Aug 2023 - Dec 2023`
**Designer/Developer | TownView Apartment Website**,

- Designed HTML/CSS website for BYU-Idaho housing options, increasing accessibility.
- Transformed housing search platforms, enhancing way information is delivered and streamlining user experience.

`Dec 2023 - Present`
**Designer/Developer | Minesweeper**,

- Designed and developed Minesweeper from scratch, showcasing proficiency in coding and problem-solving.
- Implemented critical game features, highlighting self-reliance and a strong grasp of programming concepts.

<!-- ### Footer
Last updated: April 2024 -->